# Generated by Django 5.2.6 on 2025-09-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="Featured products for 'new' section"
            ),
        ),
    ]
