# Generated by Django 5.2.6 on 2025-09-11 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_is_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalinfo",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_info",
                to="products.product",
            ),
        ),
    ]
