# Generated by Django 5.2.6 on 2025-09-15 12:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0003_alter_additionalinfo_product"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        help_text="Session key for guest users",
                        max_length=40,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who owns this comparison (null for guest sessions)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "comparison_comparisons",
            },
        ),
        migrations.CreateModel(
            name="ComparisonItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name_snapshot", models.CharField(default="", max_length=255)),
                (
                    "sku_snapshot",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "unit_price_snapshot",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "compare_price_snapshot",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("image_url_snapshot", models.URLField(blank=True, default="")),
                ("description_snapshot", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "comparison",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="comparison.comparison",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "comparison_items",
            },
        ),
        migrations.AddIndex(
            model_name="comparison",
            index=models.Index(fields=["user"], name="comparison__user_id_8dd230_idx"),
        ),
        migrations.AddIndex(
            model_name="comparison",
            index=models.Index(
                fields=["session_key"], name="comparison__session_20960a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="comparison",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("user__isnull", False),
                    ("session_key__isnull", False),
                    _connector="OR",
                ),
                name="comparison_user_or_session_required",
            ),
        ),
        migrations.AddIndex(
            model_name="comparisonitem",
            index=models.Index(
                fields=["comparison"], name="comparison__compari_6f5492_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comparisonitem",
            index=models.Index(
                fields=["product"], name="comparison__product_1efe1f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="comparisonitem",
            unique_together={("comparison", "product")},
        ),
    ]
