# Generated by Django 5.2.6 on 2025-09-20 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the person contacting us",
                        max_length=100,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address for response",
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Subject of the inquiry", max_length=200
                    ),
                ),
                ("message", models.TextField(help_text="Detailed message or inquiry")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                        ],
                        default="NEW",
                        help_text="Current status of the inquiry",
                        max_length=12,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        help_text="Priority level of the inquiry",
                        max_length=8,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the sender", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="Browser/device information"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes for admin use"
                    ),
                ),
                (
                    "response_sent",
                    models.BooleanField(
                        default=False, help_text="Whether a response has been sent"
                    ),
                ),
                (
                    "response_date",
                    models.DateTimeField(
                        blank=True, help_text="Date when response was sent", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contact Inquiry",
                "verbose_name_plural": "Contact Inquiries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="contactus_c_status_ad1271_idx",
                    ),
                    models.Index(
                        fields=["priority", "-created_at"],
                        name="contactus_c_priorit_687f91_idx",
                    ),
                    models.Index(fields=["email"], name="contactus_c_email_294cab_idx"),
                    models.Index(
                        fields=["response_sent"], name="contactus_c_respons_b43f4f_idx"
                    ),
                ],
            },
        ),
    ]
