# Generated by Django 5.2.6 on 2025-09-09 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("register", "Registration"),
                            ("password_reset", "Password Reset"),
                            ("email_verification", "Email Verification"),
                        ],
                        default="login",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("success", models.BooleanField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "email_attempted",
                    models.EmailField(
                        blank=True,
                        help_text="Email used in the attempt",
                        max_length=254,
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("invalid_email", "Invalid Email"),
                            ("invalid_password", "Invalid Password"),
                            ("account_locked", "Account Locked"),
                            ("account_inactive", "Account Inactive"),
                            ("too_many_attempts", "Too Many Attempts"),
                            ("validation_error", "Validation Error"),
                            ("invalid_token", "Invalid Token"),
                            ("expired_token", "Expired Token"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User if attempt was successful or user exists",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.DeleteModel(
            name="LoginAttempt",
        ),
        migrations.AddIndex(
            model_name="securityattempt",
            index=models.Index(
                fields=["ip_address", "timestamp"],
                name="authenticat_ip_addr_589755_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securityattempt",
            index=models.Index(
                fields=["user", "timestamp"], name="authenticat_user_id_3ab089_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityattempt",
            index=models.Index(
                fields=["success", "timestamp"], name="authenticat_success_2dd813_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityattempt",
            index=models.Index(
                fields=["attempt_type", "timestamp"],
                name="authenticat_attempt_3d8107_idx",
            ),
        ),
    ]
