# Generated by Django 5.2.6 on 2025-09-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_securityattempt_delete_loginattempt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="access_jti",
            field=models.CharField(
                blank=True,
                help_text="Current access token JTI - updated on token refresh",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="jti",
            field=models.CharField(
                blank=True,
                help_text="Refresh token JTI - used for token refresh validation",
                max_length=255,
            ),
        ),
    ]
